# Generated by Django 6.0.6 on 2026-07-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.household')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['display_order'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_rates', to='core.household')),
            ],
            options={
                'db_table': 'fx_rates',
                'unique_together': {('household', 'from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='SavingsPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_pots', to='core.household')),
            ],
            options={
                'db_table': 'savings_pots',
                'ordering': ['display_order'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effect_logic', models.CharField(choices=[('expense', 'Expense'), ('refund', 'Refund'), ('expense_from_pot', 'Expense from Pot'), ('refund_to_pot', 'Refund to Pot'), ('interest_to_pot', 'Interest earned to Pot'), ('interest_main', 'Interest earned main account')], max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='core.household')),
            ],
            options={
                'db_table': 'transaction_types',
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.household')),
            ],
            options={
                'db_table': 'years',
                'ordering': ['-year'],
                'unique_together': {('household', 'year')},
            },
        ),
    ]
