# Generated by Django 6.0.6 on 2026-07-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the month')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.household')),
            ],
            options={
                'db_table': 'monthly_checklists',
                'ordering': ['-month_year'],
                'unique_together': {('household', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('projected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid (may differ from projected)', max_digits=12, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.monthlychecklist')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
