# Generated by Django 6.0.6 on 2026-07-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('projected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('main_category', models.CharField(blank=True, max_length=255)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='core.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_expenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the skipped month')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='expenses.recurringexpense')),
            ],
            options={
                'db_table': 'recurring_expense_skips',
                'unique_together': {('expense', 'month_year')},
            },
        ),
    ]
