# Generated by Django 6.0.6 on 2026-07-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('joint_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_rows', to='config_app.year')),
            ],
            options={
                'db_table': 'monthly_ledger',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='LedgerPotValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_values', to='config_app.savingspot')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_values', to='ledger.monthlyledger')),
            ],
            options={
                'db_table': 'ledger_pot_values',
                'unique_together': {('ledger', 'pot')},
            },
        ),
    ]
