# Generated by Django 6.0.6 on 2026-07-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('term_years', models.PositiveSmallIntegerField()),
                ('initial_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fixed_period', models.PositiveSmallIntegerField(help_text='Fixed rate period in months')),
                ('new_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='core.household')),
            ],
            options={
                'db_table': 'mortgage_config',
            },
        ),
        migrations.CreateModel(
            name='PaymentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_changes', to='mortgage.mortgageconfig')),
            ],
            options={
                'db_table': 'payment_changes',
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='RateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='mortgage.mortgageconfig')),
            ],
            options={
                'db_table': 'rate_changes',
                'ordering': ['effective_date'],
            },
        ),
    ]
